-- Schema initialization for fsi-buchhaltung
CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_active_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY (token_hash)
);

CREATE TABLE IF NOT EXISTS entity_change_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  sub_entity_type VARCHAR(50) NULL,
  sub_entity_id BIGINT UNSIGNED NULL,
  field_name VARCHAR(100) NOT NULL,
  old_value TEXT NULL,
  new_value TEXT NULL,
  changed_by BIGINT UNSIGNED NOT NULL,
  changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS members (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  account BIGINT UNSIGNED,
  last_name VARCHAR(127) NOT NULL,
  first_name VARCHAR(127) NOT NULL,
  birthdate DATE NOT NULL,
  street VARCHAR(255) NOT NULL,
  street_number VARCHAR(20) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  city VARCHAR(127) NOT NULL,
  subject VARCHAR(63) NOT NULL,
  phone VARCHAR(63) NOT NULL,
  email VARCHAR(255) NOT NULL,
  notes TEXT,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  honorary TINYINT(1) NOT NULL DEFAULT 0,
  applied_at DATE NOT NULL,
  joined_at DATE NOT NULL,
  left_at DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (account) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS companies (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  street VARCHAR(255),
  street_number VARCHAR(20),
  postal_code VARCHAR(20),
  city VARCHAR(127),
  country VARCHAR(127) DEFAULT 'DE',
  iban VARCHAR(34),
  bic VARCHAR(11),
  bankname VARCHAR(127),
  vat_id VARCHAR(63),
  email VARCHAR(255),
  phone VARCHAR(63),
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS files (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  file_path VARCHAR(511) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(127) NOT NULL,
  file_size BIGINT UNSIGNED NOT NULL,
  uploaded_by BIGINT UNSIGNED NOT NULL,
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS file_attachments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  file_id BIGINT UNSIGNED NOT NULL,
  entity_type VARCHAR(63) NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  attached_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  attached_by BIGINT UNSIGNED NOT NULL,
  detached_at TIMESTAMP NULL,
  detached_by BIGINT UNSIGNED NULL,
  FOREIGN KEY (detached_by) REFERENCES users(id),
  FOREIGN KEY (attached_by) REFERENCES users(id),
  FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cost_centres (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS spheres (
  id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(127) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS receipts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  company_id BIGINT UNSIGNED,
  receipt_date DATE NOT NULL,
  receipt_number VARCHAR(100),
  description TEXT,
  status VARCHAR(15) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS receipt_positions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  receipt_id BIGINT UNSIGNED NOT NULL,
  sphere TINYINT UNSIGNED NOT NULL,
  cost_centre MEDIUMINT UNSIGNED NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  tax TINYINT UNSIGNED DEFAULT 19,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE CASCADE,
  FOREIGN KEY (cost_centre) REFERENCES cost_centres(id),
  FOREIGN KEY (sphere) REFERENCES spheres(id)
);

CREATE TABLE IF NOT EXISTS reimbursements (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  paid_by BIGINT UNSIGNED NOT NULL,
  bankname VARCHAR(127),
  account_holder VARCHAR(255),
  iban VARCHAR(34),
  bic VARCHAR(11),
  advance DECIMAL(10,2) NOT NULL DEFAULT 0,
  cash TINYINT(1) NOT NULL,
  submitted_at TIMESTAMP NOT NULL,
  checked_at TIMESTAMP,
  checked_by BIGINT UNSIGNED,
  disbursed_at TIMESTAMP,
  disbursed_by BIGINT UNSIGNED,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (paid_by) REFERENCES members(id),
  FOREIGN KEY (checked_by) REFERENCES members(id),
  FOREIGN KEY (disbursed_by) REFERENCES members(id)
);

CREATE TABLE IF NOT EXISTS reimbursement_positions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reimbursement_id BIGINT UNSIGNED NOT NULL,
  receipt_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (reimbursement_id) REFERENCES reimbursements(id) ON DELETE CASCADE,
  FOREIGN KEY (receipt_id) REFERENCES receipts(id)
);